#!/usr/bin/env bash

main () {

    s=("$@")
    len=${#s}
    sum=0
    for ((i=0; i<len; i++)); do
        c=${s:i:1}
        sum=$((sum + c ** len))
    done
    if [[ $sum == "$*" ]]; then
        echo "true"
    else
        echo "false"
    fi
#      your main function code here
}
#
#   # call main with all of the positional arguments
main "$@"

