#!/usr/bin/env bash

s=$1

case "$s" in 
  dave)
      echo hi dave
      ;;
  buddy)
      echo ohhh there he is 
      ;;
  guy)
      echo uh oh here comes trouble
      ;;
  *)
      echo idk who you are
      ;;
esac
